### ISSUE TITLE
jsome.color has no effect for me

### ISSUE THREAD

**Issue by edasque** [Javascipt/Jsome#5]
while

``` javascript
var jsome = require('jsome');
jsome.level.show = true;
jsome.level.color = 'green';
```

works. I cannot get the following to have any effect:

``` javascript
  jsome.colors = {
      'num'   : 'blue'    // stands for numbers
    , 'str'   : 'blue' // stands for strings
    , 'bool'  : 'blue'     // stands for booleans
    , 'regex' : 'blue'    // stands for regular expressions
    , 'undef' : 'grey'    // stands for undefined
    , 'null'  : 'blue'    // stands for null
    , 'attr'  : 'blue'   // objects attributes -> { attr : value }
    , 'quot'  : 'blue'  // strings quotes -> "..."
    , 'punc'  : 'blue'  // commas seperating arrays and objects values -> [ , , , ]
    , 'brack' : 'blue'  // for both {} and []
  }
  jsome.colors.attr  = ['blue' , 'bold']
```

Is there a unit test I can run that could help diagnose? node 4.2.1.

``````
├─┬ jsome@2.3.22
│ ├─┬ chalk@1.1.1
│ │ ├── ansi-styles@2.1.0
│ │ ├── escape-string-regexp@1.0.3
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.0.0
│ │ ├─┬ strip-ansi@3.0.0
│ │ │ └── ansi-regex@2.0.0
│ │ └── supports-color@2.0.0
│ ├── json-stringify-safe@5.0.1
│ └─┬ yargs@3.29.0
│   ├── camelcase@1.2.1
│   ├─┬ cliui@3.0.3
│   │ ├─┬ string-width@1.0.1
│   │ │ ├─┬ code-point-at@1.0.0
│   │ │ │ └── number-is-nan@1.0.0
│   │ │ └─┬ is-fullwidth-code-point@1.0.0
│   │ │   └── number-is-nan@1.0.0
│   │ ├─┬ strip-ansi@3.0.0
│   │ │ └── ansi-regex@2.0.0
│   │ └── wrap-ansi@1.0.0
│   ├── decamelize@1.1.1
│   ├─┬ os-locale@1.4.0
│   │ └─┬ lcid@1.0.0
│   │   └── invert-kv@1.0.0
│   ├── window-size@0.1.2
│   └── y18n@3.2.0```
``````

**Comment by Javascipt** [comment]
Thanks @edasque for reporting this issue. I started debugging and I find out that the problem was that I passed an options object to the generator of the output, and when you do 

``` javascript
   jsome.colors = { ... }
```

The reference of the options object is no longer the same as `jsome.colors`, you can assign any color you want the output will display the old settings ... 

Anyway, I've corrected this bug by passing the reference of the jsome object. Your code will work in this case :+1: , I've just published the new version on npm.

For the unit tests, I will work on them once I finish the new feature of this module (which is making this module work on the browser too).

Thanks again @edasque.

**Comment by edasque** [comment]
That fixed it but FYI:

``` javascript
      jsome.colors.attr  = ['blue' , 'bold'];
```

causes this error:

```
/Users/edasque/project/jsome_test/node_modules/jsome/lib/generator.js:92
          return chalk[isArray(color) ? color[0] : color](str);
                                                         ^

TypeError: chalk[(intermediate value)(intermediate value)(intermediate value)] is not a function
    at useColorProvider (/Users/edasque/project/jsome_test/node_modules/jsome/lib/generator.js:92:58)
    at useColorProvider (/Users/edasque/project/jsome_test/node_modules/jsome/lib/generator.js:90:18)
    at useColorProvider (/Users/edasque/project/jsome_test/node_modules/jsome/lib/generator.js:90:18)
    at colorifySpec (/Users/edasque/project/jsome_test/node_modules/jsome/lib/generator.js:76:35)
    at Object.module.exports.color.gen (/Users/edasque/project/jsome_test/node_modules/jsome/lib/generator.js:112:24)
    at Function.module.exports.jsome.parse (/Users/edasque/project/jsome_test/node_modules/jsome/script.js:45:30)
    at jsome (/Users/edasque/project/jsome_test/node_modules/jsome/script.js:31:18)
    at Request._callback (/Users/edasque/project/jsome_test/us_dotd.js:548:4)
    at Request.self.callback (/Users/edasque/project/jsome_test/node_modules/request/request.js:198:22)
```

**Comment by edasque** [comment]
Also, is something like this suppoed to work?

``` javascript
...
    , 'quot'  : 'color: #FFFF00'
...
```
