### ISSUE TITLE
jsome.colors.attr  = ['blue' , 'bold']; doesn't work

### ISSUE THREAD

**Issue by edasque** [Javascipt/Jsome#6]
``` javascript
      jsome.colors.attr  = ['blue' , 'bold'];
```

causes this error:

```
/Users/edasque/project/jsome_test/node_modules/jsome/lib/generator.js:92
          return chalk[isArray(color) ? color[0] : color](str);
                                                         ^

TypeError: chalk[(intermediate value)(intermediate value)(intermediate value)] is not a function
    at useColorProvider (/Users/edasque/project/jsome_test/node_modules/jsome/lib/generator.js:92:58)
    at useColorProvider (/Users/edasque/project/jsome_test/node_modules/jsome/lib/generator.js:90:18)
    at useColorProvider (/Users/edasque/project/jsome_test/node_modules/jsome/lib/generator.js:90:18)
    at colorifySpec (/Users/edasque/project/jsome_test/node_modules/jsome/lib/generator.js:76:35)
    at Object.module.exports.color.gen (/Users/edasque/project/jsome_test/node_modules/jsome/lib/generator.js:112:24)
    at Function.module.exports.jsome.parse (/Users/edasque/project/jsome_test/node_modules/jsome/script.js:45:30)
    at jsome (/Users/edasque/project/jsome_test/node_modules/jsome/script.js:31:18)
    at Request._callback (/Users/edasque/project/jsome_test/us_dotd.js:548:4)
    at Request.self.callback (/Users/edasque/project/jsome_test/node_modules/request/request.js:198:22)
```

**Comment by Javascipt** [comment]
You're right, It's fixed now :+1:  thank's for your help
